name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library.yml@4.0.0
    secrets: inherit

  devices:
    uses: libhal/ci/.github/workflows/deploy.yml@4.0.0
    secrets: inherit
