name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  checks:
    uses: libhal/ci/.github/workflows/library.yml@3.0.2
    secrets: inherit
  devices:
    uses: libhal/ci/.github/workflows/deploy.yml@3.0.2
    secrets: inherit
