name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - exceptions
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library_check.yml@5.x.y
    secrets: inherit

  test_deployment_:
    uses: libhal/ci/.github/workflows/deploy_all.yml@5.x.y
    secrets: inherit
